### ISSUE TITLE
Unable to recover from connection timed out

### ISSUE THREAD

**Issue by vnugent** [vnugent/rachael#5]
main] ERROR org.pircbotx.PircBotX - Exception encountered when reading next line from server
java.net.SocketException: Connection timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)

**Comment by vnugent** [comment]
https://github.com/vnugent/rachael/commit/568ded02df9fea5cd115d9bc14e179e76fcbcf0a
